# Generated by Django 5.2.1 on 2025-05-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='calle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Calle y número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas_comerciales',
            field=models.TextField(blank=True, verbose_name='Notas / Comentarios'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='España', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono fijo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_movil',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono móvil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('P', 'Particular'), ('E', 'Empresa')], default='P', max_length=1, verbose_name='Tipo de cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cif_nif',
            field=models.CharField(blank=True, max_length=20, verbose_name='CIF / NIF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre / Razón social'),
        ),
    ]
